export const CREATE_BOOK_SUCCESS 		= 'CREATE_BOOK_SUCCESS';
export const FETCH_BOOK_SUCCESS 		= 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_BY_ID_SUCCESS 	= 'FETCH_BOOK_BY_ID_SUCCESS';

export const ADD_TO_CART_SUCCESS 		= 'ADD_TO_CART_SUCCESS';
export const FETCH_CART_SUCCESS 		= 'FETCH_CART_SUCCESS';